# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  lane :playstoreinternal do
      gradle(task: "bundleRelease")
      upload_to_play_store(
        track: 'internal',
        release_status: 'draft'
      )
    end

    desc "Lane for distributing Release using Firebase"
    lane :distribute do
        gradle(task: "clean assembleRelease")
        firebase_app_distribution(
            service_credentials_file: "fastlane/google-services.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
    end

    desc "Lane for distributing Debug using Firebase"
    lane :distributeinternal do
        gradle(task: "clean assembleRelease_debug")
        firebase_app_distribution(
            service_credentials_file: "fastlane/google-services.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
    end

    desc "Lane for distributing Staging using using Firebase"
    lane :distributeinternalstg do
        gradle(task: "clean assembleRelease_stg")
        firebase_app_distribution(
            service_credentials_file: "fastlane/google-services.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
    end
end
